// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeqljbfnfubqfnsvicce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcWxqYmZuZnVicWZuc3ZpY2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjg4MDcsImV4cCI6MjA2MTgwNDgwN30.NzPY_T3qE8pXJdONDAznj5wHT_ZR2fxukiTsAYVgLzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);